import { createHash, generateKeyPairSync, sign } from "node:crypto";
import { describe, expect, it, vi } from "vitest";
import type { F10ReleaseAdapter } from "./f10";
import { F10ReleaseService, type F10Store, type ServiceState } from "./f10-service";

const bytes = new Uint8Array([1, 2, 3, 4]);
const { privateKey, publicKey } = generateKeyPairSync("ed25519");
const hash = createHash("sha256").update(bytes).digest("hex");
const signature = sign(null, Buffer.from(bytes), privateKey).toString("base64");
function fixture(overrides: Record<string, unknown> = {}) {
  const adapter: F10ReleaseAdapter = { validate: vi.fn(async()=>{}), deliver: vi.fn(async()=>({ accepted:true, downstreamReceiptId:"down-1" })), classify: vi.fn(()=>"retryable" as const), health: vi.fn(async()=>"available" as const) };
  const artifact:any={machineArtifactId:"m",mechaRunId:"run",artifactVersion:"1",mediaType:"application/octet-stream",spkId:"spk",custodyRef:"c",payloadHash:hash,artifactSignature:signature,signingKeyPem:publicKey.export({type:"spki",format:"pem"}),expiresAt:new Date(Date.now()+60_000),custodyActive:true,ucgVerdict:"PASS",mmVerdict:"MATH_VERIFIED",savantVerdict:"FIT"};
  Object.assign(artifact,overrides);
  const release:any={id:"r1",tenantId:"t",machineArtifactId:"m",destinationRef:"d",state:"QUEUED",attemptCount:0,idempotencyKey:"idem",policyHash:"policy"};
   const transitions:any[]=[]; const receipts:any[]=[]; let attempts=0; let destination:any={id:"d",active:true,adapterId:"a",adapterVersion:"1",endpoint:"https://example.com",secretRef:"secret-ref"};
   const store:F10Store={getRelease:async(id,t)=>id==="r1"&&t==="t"?release:null,getArtifact:async()=>artifact,getDestination:async()=>destination,transition:async(_i,_f,to,reason)=>{release.state=to;transitions.push({to,reason})},claimAttempt:async()=>{attempts++;return true},finalizeAttempt:async()=>true,finalizeSuccessfulAttempt:async(_i,_f,r)=>{receipts.push(r);release.state="ACKNOWLEDGED";return {status:"ACKNOWLEDGED",receipt:r}},deadLetter:async(_i,reason,n)=>{transitions.push({to:"DLQ",reason,n})}};
  const service=()=>new F10ReleaseService({store,custody:{active:async()=>artifact.custodyActive,load:async()=>bytes},adapters:new Map([["a",adapter]]),secret:{get:async()=>"TOP_SECRET"},signingSecret:"receipt-key",maxAttempts:3});
   return {adapter,artifact,release,store,transitions,receipts,attempts:()=>attempts,service,setDestination:(d:any)=>{destination=d}};
}
describe("F10ReleaseService",()=>{
   it("production-shaped store reaches ACKNOWLEDGED with one attempt and one signed receipt",async()=>{const f=fixture();const out=await f.service().process("r1","t");expect(out.state).toBe("ACKNOWLEDGED");expect(f.attempts()).toBe(1);expect(out.receipt).toMatchObject({release_id:"r1",spk_id:"spk",machine_artifact_id:"m",artifact_version:"1",payload_hash:hash,destination_identity:"d",adapter_id:"a",adapter_version:"1",attempt:1,downstream_status:"accepted",snapshot_policy_hash:"policy"});expect(out.receipt?.f10_receipt_signature).toMatch(/^[a-f0-9]{64}$/);expect(f.receipts).toHaveLength(1)});
   it("duplicate or stale acknowledgement never creates a second authoritative receipt",async()=>{const f=fixture();const first=await f.service().process("r1","t");f.release.state="ACKNOWLEDGED";f.release.receipt=first.receipt;const second=await f.service().process("r1","t");expect(second.receipt).toEqual(first.receipt);expect(f.receipts).toHaveLength(1);const g=fixture();g.store.finalizeSuccessfulAttempt=async()=>({status:"STALE"});const stale=await g.service().process("r1","t");expect(stale.state).toBe("QUEUED");expect(g.receipts).toHaveLength(0)});
   it("does not report acknowledgement when atomic release transition fails",async()=>{const f=fixture();f.store.finalizeSuccessfulAttempt=async()=>{throw new Error("release is no longer dispatching")};expect((await f.service().process("r1","t")).state).toBe("QUEUED");expect(f.receipts).toHaveLength(0)});
  it("rechecks revocation before deliver",async()=>{const f=fixture();let reads=0;f.store.getDestination=async()=>{reads++;return reads===1?{id:"d",active:true,adapterId:"a",endpoint:"https://example.com",secretRef:"x"}:{id:"d",active:false}};expect((await f.service().process("r1","t")).state).toBe("BLOCKED");expect(f.adapter.deliver).not.toHaveBeenCalled()});
  it("retries retryable errors then dead-letters at max",async()=>{const f=fixture();f.adapter.deliver=vi.fn(async()=>{throw new Error("timeout")});let n=0;f.store.getRelease=async()=>({...f.release,state:"QUEUED",attemptCount:n++});const states: ServiceState[]=[];f.store.transition=async(_i,_f,to)=>{states.push(to)};expect((await f.service().process("r1","t")).state).toBe("QUEUED");expect((await f.service().process("r1","t")).state).toBe("QUEUED");expect((await f.service().process("r1","t")).state).toBe("DEAD_LETTERED");expect(states).toContain("DEAD_LETTERED")});
  it("permanent failure does not retry and accepted:false is not acknowledgement",async()=>{const f=fixture();f.adapter.classify=vi.fn(()=>"permanent" as const);f.adapter.deliver=vi.fn(async()=>{throw new Error("401")});expect((await f.service().process("r1","t")).state).toBe("FAILED_PERMANENT");expect(f.adapter.deliver).toHaveBeenCalledTimes(1);const g=fixture();g.adapter.deliver=vi.fn(async()=>({accepted:false}));expect((await g.service().process("r1","t")).state).toBe("FAILED_PERMANENT")});
  it.each(["payloadHash","artifactSignature","expiresAt","ucgVerdict","mmVerdict","savantVerdict","custodyActive"])("invalid %s blocks with zero adapter calls",(field)=>{const value:any={payloadHash:"sha256:"+"0".repeat(64),artifactSignature:"bad",expiresAt:new Date(0),ucgVerdict:"FAIL",mmVerdict:"FAIL",savantVerdict:"FAIL",custodyActive:false};const f=fixture({[field]:value[field]});return f.service().process("r1","t").then(out=>{expect(out.state).toBe("BLOCKED");expect(f.adapter.deliver).not.toHaveBeenCalled()})});
  it("never exposes the secret in result, transitions, or receipt",async()=>{const f=fixture();const out=await f.service().process("r1","t");expect(JSON.stringify({out,transitions:f.transitions,receipts:f.receipts})).not.toContain("TOP_SECRET")});
  it("rejects cross-tenant release lookup",async()=>{const f=fixture();await expect(f.service().process("r1","other")).rejects.toThrow("release not found")});
});