import { Router, type IRouter } from "express";
import healthRouter from "./health";
import meRouter from "./me";
import sessionsRouter from "./sessions";
import artifactsRouter from "./artifacts";
import billingRouter from "./billing";
import pricingRouter from "./pricing";
import cronRouter from "./cron";
import verifyRouter from "./verify";
import exemplarsRouter from "./exemplars";
import harnessRouter from "./harness";
import promptsRouter from "./prompts";
import exportsRouter from "./exports";
import badgesRouter from "./badges";
import ingestRouter from "./ingest";
import cartridgeRouter from "./cartridge";
import orgsRouter from "./orgs";
import activityRouter from "./activity";
import costRouter from "./cost";
import notificationsRouter from "./notifications";
import integrationsRouter from "./integrations";
import onboardingRouter from "./onboarding";
import f1000Router from "./f1000";
import f0Router from "./f0";
import staffAuthRouter from "./staff-auth";
import magnetRouter from "./magnet";

const router: IRouter = Router();

router.use(healthRouter);
router.use(staffAuthRouter);
router.use(magnetRouter);
router.use(meRouter);
router.use(onboardingRouter);
router.use(promptsRouter);
router.use(exportsRouter);
router.use(badgesRouter);
router.use(sessionsRouter);
router.use(artifactsRouter);
router.use(billingRouter);
router.use(pricingRouter);
router.use(cronRouter);
router.use(verifyRouter);
router.use(exemplarsRouter);
router.use(harnessRouter);
router.use(ingestRouter);
router.use(cartridgeRouter);
router.use(orgsRouter);
router.use(activityRouter);
router.use(costRouter);
router.use(notificationsRouter);
router.use(integrationsRouter);
router.use(f1000Router);
router.use(f0Router);

export default router;
