import { Sparkles } from "lucide-react";

const PROVIDER_LABEL: Record<string, string> = {
  claude: "Claude",
  openai: "OpenAI",
  gemini: "Gemini",
};

interface Props {
  provider?: string | null;
  modelId?: string | null;
  testId?: string;
  className?: string;
}

export function GeneratedBy({ provider, modelId, testId, className }: Props) {
  if (!provider) return null;
  const label = PROVIDER_LABEL[provider] ?? provider;
  return (
    <div
      data-testid={testId ?? "generated-by"}
      className={
        "flex items-center gap-1.5 font-mono text-[10px] text-muted-foreground " +
        (className ?? "")
      }
      title={modelId ?? undefined}
    >
      <Sparkles className="h-3 w-3" />
      <span className="uppercase tracking-wider">Generated by</span>
      <span className="text-foreground/80">{label}</span>
      {modelId ? (
        <>
          <span>·</span>
          <span className="text-foreground/70">{modelId}</span>
        </>
      ) : null}
    </div>
  );
}
